theme: jekyll-theme-minimal
#remote_theme: wbadart/jekyll-theme-dark-minimal
#plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
#  - jekyll-include-cache
#  - jekyll-remote-theme
